---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parse_node(parse_node)
	generate_code(generate_code)
	reconstruct_rule(reconstruct_rule)
	__end__([<p>__end__</p>]):::last
	__start__ --> parse_node;
	generate_code --> reconstruct_rule;
	parse_node --> generate_code;
	reconstruct_rule --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
